image: docker:latest
services:
  - docker:dind

variables:
    CX_PROJECT: \CxServer\SP\Checkmarx\riches-test.net

stages:
  - sast
#  - results

#sast-scan:
#  stage: sast
#  image:
#    name: custodela/checkmarx-cli
#    entrypoint: ['']
#  script:
#    - ${CX_CLI} Scan -v -CxServer ${CHECKMARX_BASE_URL} -projectName ${CX_PROJECT} -CxUser ${CHECKMARX_USERNAME} -CxPassword ${CHECKMARX_PASSWORD} -Locationtype folder -locationpath ${CI_PROJECT_DIR} -ReportXML cx.xml
#    - cp /cx/CxConsolePlugin-8.80.0/riches.net/cx.xml .
#  only:
#    - master
#  artifacts:
#    paths:
#      - ./cx.xml

cx-scan:
  stage: sast
  image:
    name: custodela/cx-flow:cmd
    entrypoint: ['']
  script:
    - echo ${AUTOMATION_YML} | base64 -d > application.yml
    - java -jar /cx-flow-cmd-1.2.jar
        --spring.config.location=./application.yml
        --scan
        --cx-team="\CxServer\SP\Checkmarx"
        --cx-project="Abc1234"
        --app=ABCAPP
        --f=.
        --bug-tracker=Json
#        --logging.level.org.springframework.web.client.RestTemplate=TRACE
#        --logging.level.com.checkmarx.flow.service=DEBUG
#        --logging.level.org.apache.http.wire=TRACE
#  only:
#    - master

#cx-results:
#  stage: results
#  image:
#    name: custodela/cx-flow:cmd
#    entrypoint: ['']
#  script:
#    - ${MACHINA_CLI}
#        --project
#        --cx-team="\CxServer\SP\Checkmarx"
#        --cx-project="Abc1234"
#        --app=ABCAPP
#        --cx-flow.break-build=true
#  only:
#    - master

    